### PR TITLE
[TASK] Require individual typo3/cms-* packages

### PR DESCRIPTION
**Pull request by mbrodala**

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Thanks Mathias - it technically also requires typo3/cms-fluid since we depend on the cache implementation it adds. And I would definitely appreciate another follow-up to add the 9.x branch as supported, which I'm sure it is :)

**Comment by mbrodala** [comment]
Very likely. But first we'll need a release with this change since the package cannot really be used with split-package installations otherwise.

**Review by NamelessCoder — APPROVED** [review]

**Comment by NamelessCoder** [comment]
1.2.0 tagged and pushed!

**Comment by mbrodala** [comment]
Thanks for the quick release. :-)

**Pull request merged**
