### PR TITLE
[TASK] move ext_icon.svg to Resources/Public

### PR DESCRIPTION
**Pull request by infabo**
In secure-web setups only assets from Public are available.

### CODE REVIEW

**Comment by mbrodala** [comment]
Thanks.

**Comment by NamelessCoder** [comment]
Thanks for the patch @infabo - and for taking care of this one @mbrodala. I've changed the repository settings so we do squash-merge by default and please keep an eye on the TYPO3 CMS commit CGL being followed, I'm really nitpicking here but subjects should start with an uppercase letter after the prefix ;)

**Comment by mbrodala** [comment]
Sure thing. I was more worried about the icon not working at all. ;-)

**Comment by NamelessCoder** [comment]
Like we say, "make it work then make it pretty" ^^

**Pull request merged**
